services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: events_app
    command: poetry run python event_api/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=changeme
    depends_on:
      - db
    volumes:
      - ./event_api:/app/event_api

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local